version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.13.3
    working_directory: /go/src/github.com/heroku/shaas
    steps:
      - checkout
      - setup_remote_docker
      - run: go get -v -t -d ./...
      - run: go test -v ./... -ftest

